version: "3.9"
services:
    todo-list:
        build:
            dockerfile: Dockerfile
            context: .
            target: dev
        volumes:
            - ../..:/opt/todo-list/src
        ports:
            - "8081:8000"
        networks:
            - todolist

    db:
        image: mysql:8.0.26
        entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        container_name: mysql_go
        environment:
            MYSQL_USER: mysql_go
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: todoGo
        ports:
            - "4306:3306"
        networks:
            - todolist
        depends_on:
          - todo-list

networks:
  todolist:
    driver: bridge